config:
  aws:region: us-east-1
  nounhub:googleClientId: 852318184489-s1t7vibfkfu91ggcflgi7bjl5qiarcl4.apps.googleusercontent.com
  nounhub:certificateArn: arn:aws:acm:us-east-1:590183965738:certificate/9b068ed9-7828-4c33-b464-23a29e4e7991
